Try with MISSING

diff --git a/.github/workflows/api-deploy.yml b/.github/workflows/api-deploy.yml
--- a/.github/workflows/api-deploy.yml
+++ b/.github/workflows/api-deploy.yml
@@ -97,7 +97,11 @@ jobs:
 
           while [[ $failures -lt 2 ]]; do
             set +e -x
-            result_msg=$({ echo "Something something something aoeigjaiow MISSINGfigoegowh o weigoj \niowe gioe"; exit 1; })
+            if [[ $failures -eq 1 ]]; do
+              result_msg=$(aws ecs wait services-stable --cluster $CLUSTER_ID --services $SVC_ID)
+            else
+              result_msg=$({ echo "Something something something aoeigjaiow MISSINGfigoegowh o weigoj \niowe gioe"; exit 1; })
+            fi
             result_code=$?
             set -e +x
 
@@ -106,6 +110,7 @@ jobs:
             elif [[ "${result_msg}" =~ "MISSING" ]]; then
               # This happens sometimes when the script runs too quickly after terraform apply.
               # Sleep for a little bit and try again without considering it a retry.
+              echo "Sleeping for 5 seconds"
               sleep 5
             else
               ((failures++))
